### ISSUE TITLE
Implemeting context based correction

### ISSUE THREAD

**Issue by nvs-abhilash** [nvs-abhilash/CorrectMe#20]
This is by far the most important thing remaining on our part to make this project presentable. I believe after we close all the preceding issues. We should completely focus on closing this. To close this we need to do the following things:

1. Research and find useful algorithms that gives contextual information.
2. Use it to provide **context based** suggestions.

OR find ways to achieve both. :/

@piyush-jaiswal I think we should start finding ways to implement it ASAP. Please add comments on your ideas of implementing these. I would add mine soon.

**Comment by piyush-jaiswal** [comment]
I think using n-grams would be a good start. We could implement something like trigrams on a relevant corpus and evaluate the results. In future when we implement other algorithms, this would prove a good baseline for us. What do you think @nvs-abhilash?

**Comment by piyush-jaiswal** [comment]
Hi @nvs-abhilash, I found [this](https://www.ngrams.info/intro.asp) ngrams dataset derived from the COCA corpus. [Here's](https://www.ngrams.info/compare.asp) a comparision with the google ngrams dataset. [This](https://www.ngrams.info/samples_coca1.asp) is the link to their level1 freely available dataset. Let me know what you think.

**Comment by nvs-abhilash** [comment]
@piyush-jaiswal Thanks for this. Looks a good approach. So from a higher level of understanding we should use this dataset to create a n-gram based model so that we can predict the most probable word for the last in-correct word in the textbox, right?

**Comment by piyush-jaiswal** [comment]
Yes, that's correct. For this I had a few varying approaches in mind:

1. Select the top 'k' predictions from the model and suggest the one that has the least edit distance to the incorrect word. (the model's most confident prediction might not always be close to the incorrect word)

2. Select all the words that are within 'ed' edit distance from the incorrect word (most probably using BK trees) and suggest the the word to which the model assigns the highest score.

3. Come up with some sort of hybrid approach combining the two methods above and assign some pre-defined weights to the edit distance value and the prediction value in order to compute the final score. (Final score = w1 * ed + w2 * pred)

I think this would be done at prediction time and could be useful for not just ngrams but other models based on different approaches that we come up with. What are your thoughts on this @nvs-abhilash?

**Comment by nvs-abhilash** [comment]
This looks good starting point. Let me build a baseline model and submit a PR in 1-2 days, then we can discuss the challenges going forward with this approach.
